# Generated by Django 5.1 on 2024-09-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_order_phone_alter_order_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
